apiVersion: v1
kind: PersistentVolume
metadata:
  name: utsav-mysql-persistent-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-pv
  gcePersistentDisk:
    pdName: pv-disk
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
