apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: utsav-mysql-statefulset
spec:
  serviceName: utsav-mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app: utsav-mysql
  template:
    metadata:
      labels:
        app: utsav-mysql
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: utsav-mysql-pv-claim
      
      containers:
        - name: utsav-mysql
          image: utsavaishuverma/utsav-mysql-image:1
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql